version: "3.8"
services:
  authz:
    build: ./authz_server
    ports:
    - "5001:5001"
  backend:
    build: ./backend_server
    ports:
    - "9091:9091"
  envoy:
    build: ./envoy
    command: envoy -c /etc/envoy/envoy.yaml -l trace
    ports:
      - "8081:8081"